[package]
name = "duplihere"
version = "0.2.0"
authors = ["Tony Asleson <tony.asleson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rags-rs = "0.1.4"
glob = "0.3.0"